F(by) talk and matching blog post: JuliaLang: The Ingredients for a Composable Programming Language
oxinabox/oxinabox.github.io pull request #11
Opened 2020-02-08 15:49 UTC by oxinabox

2020-02-08 20:34 UTC, karajan9 requested changes
I really like the content and think it is well thought out. The blog still reads to me more like talk slides than a blog post, maybe it would be beneficial to form it into a more flowing text?

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +I trust the reader will forgived me.
typo

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +## What do I mean by composable ?
extra space before ?

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +The theory I prose heremay sound counter-intuitive
here may

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +are because the language has not just good features, but **weak and missing features.**
Not sure how the sentence was intended, it sounds off to me.

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +But what happens if one has package:
*a package

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +then julia throws an error.
*Julia

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +There is no name collision if both names *are* overloaded the from the same namespace.
Seems like a weird emphasis to me?

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +Name collisions makes package authors to come together and create base package (like `StatsBase`) and agree on what the functions mean.
Mix of singular and plural (collisions, makes),
package -> packages

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +One can even overload functions from multiple namespaces if you want;
Maybe both times "you" or "one"?

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +Julia uses a JIT compiler, so  even compilation errors don't arive til run-time.
*arrive *until

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +Testing julia code is important.
*Julia

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +If code-paths are not covered in tests their is almost nothing in the language itself to protect them from having any kind of error.
*there

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +So its important to have Continuous Integration and other tooling all setup
*it's
*set up
*.

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +But if it is easier to make a package, than it is to not, then it does.
Maybe there's another way to put this?

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +Its not a silver bullet but its one more push in the right direction.
*it's

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +Such as [Eli Bendersky's blog post on the expression problem](https://eli.thegreenplace.net/2016/the-expression-problem-and-its-solutions#is-multiple-dispatch-necessary-to-cleanly-solve-the-expressio
Ending .

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +Some languages (e.g. Java) require that methods literally be places inside the same file as the class.
*placed

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +### We would like to use some coode from a library
*code

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +{% highlight julia %}
This doesn't render right.

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> + - This could mean adding a lot of code for them to maintain
Either end all points with "." or none?

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +##### Varient: Monkey-patch
*Variant

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +(NB: this example is **not** valid julia code)
*Julia

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +If someone else implements `DuckWithChickenSupport`, and I want to use both there code and mine, what do?
"what do I do"?

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +## But does this happen in the wild?
Maybe specify you are not talking about ducks and swans in the wild ;-)

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +If you look at a list of BLAS, methods you will see just this, encoded in the function name
remove ,

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +This is pretty good: its a reasonable assumption that the types are going to an important case.
*it's

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +Its a good time to be inventing new languages.
It's

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +Its good for me because I like cool new things.
It's

2020-02-08 20:34 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +I’ld just really like those new languages to please have:
*I'd

2020-02-08 20:48 UTC, oxinabox commented on _posts/2020-02-08-whycompositionaljulia.md
> +There is no name collision if both names *are* overloaded the from the same namespace.
Yes, looks like a left over from a earlier version of this sentenced.
Rephrases and moved empisis

2020-02-08 20:55 UTC, oxinabox commented on _posts/2020-02-08-whycompositionaljulia.md
> +Testing julia code is important.
I am going to stick to lower-case julia
It makes it less like a person's name.

2020-02-08 20:58 UTC, karajan9 commented on _posts/2020-02-08-whycompositionaljulia.md
> +Testing julia code is important.
I remember reading somewhere that the name of the language is supposed to be "Julia" and "julia" refers to the executable. I can't find it right now though, so I guess it's fine either way ;-)

2020-02-08 21:10 UTC, oxinabox commented on _posts/2020-02-08-whycompositionaljulia.md
> +{% highlight julia %}
It does in published form.

2020-02-08 21:31 UTC, oxinabox commented
> The blog still reads to me more like talk slides than a blog post, maybe it would be beneficial to form it into a more flowing text?

Having done that before it takes more time than I have right now.

The transition from: [these slides](https://rawcdn.githack.com/oxinabox/oxinabox.github.io/2cab1a7528cd5e2395de03ffc7767a4006d5ea15/_drafts/PyDataCambridgeMeetup2019/JuliaLangFeatures.slides.html) to the pair of Emergent Features of Julia Lang blog posts:
https://invenia.github.io/blog/2019/10/30/julialang-features-part-1/
and https://invenia.github.io/blog/2019/11/06/julialang-features-part-2/
took multiple people-days.

Which is why this is going out on my blog rather than Invenia's.
Because the company has a different kind of reputation to maintain.

2020-02-09 06:25 UTC, karajan9 commented
Fair enough! Thanks for doing this in the first place.

2020-02-09 09:03 UTC, cormullion commented
Is there a latest version that I can look through?

2020-02-09 11:47 UTC, oxinabox commented
> Is there a latest version that I can look through?

Latest version  is what I pushed.
I don't have an easy way to show previews as it will look in final.
(What I do is spin up local jekyll)

2020-02-09 11:56 UTC, cormullion commented
I'll give it a read now... give me till midday :)

2020-02-09 12:02 UTC, cormullion commented
Here's a few corrections:

11 someone else's

26 details on some of

92 overloaded are the from ??

163 enclined => inclined

183 benifits => benefits

194 finding other resource to read on it => other resouces to read up about it?

450 someone elses library => someone else's

582  its a => it's

641 what ever  => whatever 

We need a better way to do proof-reading! :)

2020-02-09 12:34 UTC, oxinabox commented
Thanks all for the help, releasing now

2020-02-09 12:34 UTC, merged